importing the different necessary packages

In [8]:
import pandas as pd
import requests
import json
import urllib3
from pandas import json_normalize

*Requirement: Pull in data from the API*

then I'm loading in the API. 

I tried the df.head() and that only resulted in one row returned, so I'm trying to just interact with the API with print(data) as a test.

In [22]:
url = "https://api.spacexdata.com/v4/rockets"
response = requests.get(url)
data = response.json()
print(data)

[{'height': {'meters': 22.25, 'feet': 73}, 'diameter': {'meters': 1.68, 'feet': 5.5}, 'mass': {'kg': 30146, 'lb': 66460}, 'first_stage': {'thrust_sea_level': {'kN': 420, 'lbf': 94000}, 'thrust_vacuum': {'kN': 480, 'lbf': 110000}, 'reusable': False, 'engines': 1, 'fuel_amount_tons': 44.3, 'burn_time_sec': 169}, 'second_stage': {'thrust': {'kN': 31, 'lbf': 7000}, 'payloads': {'composite_fairing': {'height': {'meters': 3.5, 'feet': 11.5}, 'diameter': {'meters': 1.5, 'feet': 4.9}}, 'option_1': 'composite fairing'}, 'reusable': False, 'engines': 1, 'fuel_amount_tons': 3.38, 'burn_time_sec': 378}, 'engines': {'isp': {'sea_level': 267, 'vacuum': 304}, 'thrust_sea_level': {'kN': 420, 'lbf': 94000}, 'thrust_vacuum': {'kN': 480, 'lbf': 110000}, 'number': 1, 'type': 'merlin', 'version': '1C', 'layout': 'single', 'engine_loss_max': 0, 'propellant_1': 'liquid oxygen', 'propellant_2': 'RP-1 kerosene', 'thrust_to_weight': 96}, 'landing_legs': {'number': 0, 'material': None}, 'payload_weights': [{'id': 'leo', 'name': 'Low Earth Orbit', 'kg': 450, 'lb': 992}], 'flickr_images': ['https://imgur.com/DaCfMsj.jpg', 'https://imgur.com/azYafd8.jpg'], 'name': 'Falcon 1', 'type': 'rocket', 'active': False, 'stages': 2, 'boosters': 0, 'cost_per_launch': 6700000, 'success_rate_pct': 40, 'first_flight': '2006-03-24', 'country': 'Republic of the Marshall Islands', 'company': 'SpaceX', 'wikipedia': 'https://en.wikipedia.org/wiki/Falcon_1', 'description': 'The Falcon 1 was an expendable launch system privately developed and manufactured by SpaceX during 2006-2009. On 28 September 2008, Falcon 1 became the first privately-developed liquid-fuel launch vehicle to go into orbit around the Earth.', 'id': '5e9d0d95eda69955f709d1eb'}, {'height': {'meters': 70, 'feet': 229.6}, 'diameter': {'meters': 3.7, 'feet': 12}, 'mass': {'kg': 549054, 'lb': 1207920}, 'first_stage': {'thrust_sea_level': {'kN': 7607, 'lbf': 1710000}, 'thrust_vacuum': {'kN': 8227, 'lbf': 1849500}, 'reusable': True, 'engines': 9, 'fuel_amount_tons': 385, 'burn_time_sec': 162}, 'second_stage': {'thrust': {'kN': 934, 'lbf': 210000}, 'payloads': {'composite_fairing': {'height': {'meters': 13.1, 'feet': 43}, 'diameter': {'meters': 5.2, 'feet': 17.1}}, 'option_1': 'dragon'}, 'reusable': False, 'engines': 1, 'fuel_amount_tons': 90, 'burn_time_sec': 397}, 'engines': {'isp': {'sea_level': 288, 'vacuum': 312}, 'thrust_sea_level': {'kN': 845, 'lbf': 190000}, 'thrust_vacuum': {'kN': 914, 'lbf': 205500}, 'number': 9, 'type': 'merlin', 'version': '1D+', 'layout': 'octaweb', 'engine_loss_max': 2, 'propellant_1': 'liquid oxygen', 'propellant_2': 'RP-1 kerosene', 'thrust_to_weight': 180.1}, 'landing_legs': {'number': 4, 'material': 'carbon fiber'}, 'payload_weights': [{'id': 'leo', 'name': 'Low Earth Orbit', 'kg': 22800, 'lb': 50265}, {'id': 'gto', 'name': 'Geosynchronous Transfer Orbit', 'kg': 8300, 'lb': 18300}, {'id': 'mars', 'name': 'Mars Orbit', 'kg': 4020, 'lb': 8860}], 'flickr_images': ['https://farm1.staticflickr.com/929/28787338307_3453a11a77_b.jpg', 'https://farm4.staticflickr.com/3955/32915197674_eee74d81bb_b.jpg', 'https://farm1.staticflickr.com/293/32312415025_6841e30bf1_b.jpg', 'https://farm1.staticflickr.com/623/23660653516_5b6cb301d1_b.jpg', 'https://farm6.staticflickr.com/5518/31579784413_d853331601_b.jpg', 'https://farm1.staticflickr.com/745/32394687645_a9c54a34ef_b.jpg'], 'name': 'Falcon 9', 'type': 'rocket', 'active': True, 'stages': 2, 'boosters': 0, 'cost_per_launch': 50000000, 'success_rate_pct': 98, 'first_flight': '2010-06-04', 'country': 'United States', 'company': 'SpaceX', 'wikipedia': 'https://en.wikipedia.org/wiki/Falcon_9', 'description': 'Falcon 9 is a two-stage rocket designed and manufactured by SpaceX for the reliable and safe transport of satellites and the Dragon spacecraft into orbit.', 'id': '5e9d0d95eda69973a809d1ec'}, {'height': {'meters': 70, 'feet': 229.6}, 'diameter': {'meters': 12.2, 'feet': 39.9}, 'mass': {'kg': 1420788, 'lb': 3125735}, 'first_stage': {'thrust_sea_level': {'kN': 22819, 'lbf': 5130000}, 'thrust_vacuum': {'kN': 24681, 'lbf': 5548500}, 'reusable': True, 'engines': 27, 'fuel_amount_tons': 1155, 'burn_time_sec': 162}, 'second_stage': {'thrust': {'kN': 934, 'lbf': 210000}, 'payloads': {'composite_fairing': {'height': {'meters': 13.1, 'feet': 43}, 'diameter': {'meters': 5.2, 'feet': 17.1}}, 'option_1': 'dragon'}, 'reusable': False, 'engines': 1, 'fuel_amount_tons': 90, 'burn_time_sec': 397}, 'engines': {'isp': {'sea_level': 288, 'vacuum': 312}, 'thrust_sea_level': {'kN': 845, 'lbf': 190000}, 'thrust_vacuum': {'kN': 914, 'lbf': 205500}, 'number': 27, 'type': 'merlin', 'version': '1D+', 'layout': 'octaweb', 'engine_loss_max': 6, 'propellant_1': 'liquid oxygen', 'propellant_2': 'RP-1 kerosene', 'thrust_to_weight': 180.1}, 'landing_legs': {'number': 12, 'material': 'carbon fiber'}, 'payload_weights': [{'id': 'leo', 'name': 'Low Earth Orbit', 'kg': 63800, 'lb': 140660}, {'id': 'gto', 'name': 'Geosynchronous Transfer Orbit', 'kg': 26700, 'lb': 58860}, {'id': 'mars', 'name': 'Mars Orbit', 'kg': 16800, 'lb': 37040}, {'id': 'pluto', 'name': 'Pluto Orbit', 'kg': 3500, 'lb': 7720}], 'flickr_images': ['https://farm5.staticflickr.com/4599/38583829295_581f34dd84_b.jpg', 'https://farm5.staticflickr.com/4645/38583830575_3f0f7215e6_b.jpg', 'https://farm5.staticflickr.com/4696/40126460511_b15bf84c85_b.jpg', 'https://farm5.staticflickr.com/4711/40126461411_aabc643fd8_b.jpg'], 'name': 'Falcon Heavy', 'type': 'rocket', 'active': True, 'stages': 2, 'boosters': 2, 'cost_per_launch': 90000000, 'success_rate_pct': 100, 'first_flight': '2018-02-06', 'country': 'United States', 'company': 'SpaceX', 'wikipedia': 'https://en.wikipedia.org/wiki/Falcon_Heavy', 'description': 'With the ability to lift into orbit over 54 metric tons (119,000 lb)--a mass equivalent to a 737 jetliner loaded with passengers, crew, luggage and fuel--Falcon Heavy can lift more than twice the payload of the next closest operational vehicle, the Delta IV Heavy, at one-third the cost.', 'id': '5e9d0d95eda69974db09d1ed'}, {'height': {'meters': 118, 'feet': 387}, 'diameter': {'meters': 9, 'feet': 30}, 'mass': {'kg': 1335000, 'lb': 2943000}, 'first_stage': {'thrust_sea_level': {'kN': 128000, 'lbf': 28775544}, 'thrust_vacuum': {'kN': 138000, 'lbf': 31023634}, 'reusable': True, 'engines': 37, 'fuel_amount_tons': 3300, 'burn_time_sec': None}, 'second_stage': {'thrust': {'kN': 1957, 'lbf': 440000}, 'payloads': {'composite_fairing': {'height': {'meters': None, 'feet': None}, 'diameter': {'meters': None, 'feet': None}}, 'option_1': 'Spaceship'}, 'reusable': True, 'engines': 6, 'fuel_amount_tons': 1200, 'burn_time_sec': None}, 'engines': {'isp': {'sea_level': 330, 'vacuum': 380}, 'thrust_sea_level': {'kN': 1780, 'lbf': 400000}, 'thrust_vacuum': {'kN': 1960, 'lbf': 440000}, 'number': 37, 'type': 'raptor', 'version': '', 'layout': None, 'engine_loss_max': None, 'propellant_1': 'liquid oxygen', 'propellant_2': 'liquid methane', 'thrust_to_weight': 107}, 'landing_legs': {'number': 6, 'material': 'stainless steel'}, 'payload_weights': [{'id': 'leo', 'name': 'Low Earth Orbit', 'kg': 150000, 'lb': 330000}, {'id': 'mars', 'name': 'Mars Orbit', 'kg': 100000, 'lb': 220000}, {'id': 'moon', 'name': 'Moon Orbit', 'kg': 100000, 'lb': 220000}], 'flickr_images': ['https://live.staticflickr.com/65535/48954138962_ee541e6755_b.jpg', 'https://live.staticflickr.com/65535/48953946911_e60c5bcc5c_b.jpg', 'https://live.staticflickr.com/65535/48954138922_9c42173f08_b.jpg', 'https://live.staticflickr.com/65535/48953947006_313f01ec93_b.jpg'], 'name': 'Starship', 'type': 'rocket', 'active': False, 'stages': 2, 'boosters': 0, 'cost_per_launch': 7000000, 'success_rate_pct': 0, 'first_flight': '2021-12-01', 'country': 'United States', 'company': 'SpaceX', 'wikipedia': 'https://en.wikipedia.org/wiki/SpaceX_Starship', 'description': 'Starship and Super Heavy Rocket represent a fully reusable transportation system designed to service all Earth orbit needs as well as the Moon and Mars. This two-stage vehicle — composed of the Super Heavy rocket (booster) and Starship (ship) — will eventually replace Falcon 9, Falcon Heavy and Dragon.', 'id': '5e9d0d96eda699382d09d1ee'}]

Ok this worked. 

When I did df.head() that still didn't work(only returned one row) so I asked for online help. Suggestion was to check if the data was a dictionary, and if so, to convert it to a list. This also didn't work, so it's commented out. I ended up using a different API

In [10]:

#if isinstance(data, dict):
#    data = [data]

*Requirement: show first 4 rows of dataframe*

if things were going as planned, this would be my next line of code to get first 4 rows:

In [24]:
rockets = pd.DataFrame(data)
rockets.head(4)

,height,diameter,mass,first_stage,second_stage,engines,landing_legs,payload_weights,flickr_images,name,...,stages,boosters,cost_per_launch,success_rate_pct,first_flight,country,company,wikipedia,description,id
0,"{'meters': 22.25, 'feet': 73}","{'meters': 1.68, 'feet': 5.5}","{'kg': 30146, 'lb': 66460}","{'thrust_sea_level': {'kN': 420, 'lbf': 94000}...","{'thrust': {'kN': 31, 'lbf': 7000}, 'payloads'...","{'isp': {'sea_level': 267, 'vacuum': 304}, 'th...","{'number': 0, 'material': None}","[{'id': 'leo', 'name': 'Low Earth Orbit', 'kg'...","[https://imgur.com/DaCfMsj.jpg, https://imgur....",Falcon 1,...,2,0,6700000,40,2006-03-24,Republic of the Marshall Islands,SpaceX,https://en.wikipedia.org/wiki/Falcon_1,The Falcon 1 was an expendable launch system p...,5e9d0d95eda69955f709d1eb
1,"{'meters': 70, 'feet': 229.6}","{'meters': 3.7, 'feet': 12}","{'kg': 549054, 'lb': 1207920}","{'thrust_sea_level': {'kN': 7607, 'lbf': 17100...","{'thrust': {'kN': 934, 'lbf': 210000}, 'payloa...","{'isp': {'sea_level': 288, 'vacuum': 312}, 'th...","{'number': 4, 'material': 'carbon fiber'}","[{'id': 'leo', 'name': 'Low Earth Orbit', 'kg'...",[https://farm1.staticflickr.com/929/2878733830...,Falcon 9,...,2,0,50000000,98,2010-06-04,United States,SpaceX,https://en.wikipedia.org/wiki/Falcon_9,Falcon 9 is a two-stage rocket designed and ma...,5e9d0d95eda69973a809d1ec
2,"{'meters': 70, 'feet': 229.6}","{'meters': 12.2, 'feet': 39.9}","{'kg': 1420788, 'lb': 3125735}","{'thrust_sea_level': {'kN': 22819, 'lbf': 5130...","{'thrust': {'kN': 934, 'lbf': 210000}, 'payloa...","{'isp': {'sea_level': 288, 'vacuum': 312}, 'th...","{'number': 12, 'material': 'carbon fiber'}","[{'id': 'leo', 'name': 'Low Earth Orbit', 'kg'...",[https://farm5.staticflickr.com/4599/385838292...,Falcon Heavy,...,2,2,90000000,100,2018-02-06,United States,SpaceX,https://en.wikipedia.org/wiki/Falcon_Heavy,With the ability to lift into orbit over 54 me...,5e9d0d95eda69974db09d1ed
3,"{'meters': 118, 'feet': 387}","{'meters': 9, 'feet': 30}","{'kg': 1335000, 'lb': 2943000}","{'thrust_sea_level': {'kN': 128000, 'lbf': 287...","{'thrust': {'kN': 1957, 'lbf': 440000}, 'paylo...","{'isp': {'sea_level': 330, 'vacuum': 380}, 'th...","{'number': 6, 'material': 'stainless steel'}","[{'id': 'leo', 'name': 'Low Earth Orbit', 'kg'...",[https://live.staticflickr.com/65535/489541389...,Starship,...,2,0,7000000,0,2021-12-01,United States,SpaceX,https://en.wikipedia.org/wiki/SpaceX_Starship,Starship and Super Heavy Rocket represent a fu...,5e9d0d96eda699382d09d1ee

this looks ugly, apparently this is a nested dictionary. Json normalize will hopefully help

In [27]:
rockets = pd.json_normalize(data)

rockets = pd.DataFrame(data)
rockets.head(4)

,height,diameter,mass,first_stage,second_stage,engines,landing_legs,payload_weights,flickr_images,name,...,stages,boosters,cost_per_launch,success_rate_pct,first_flight,country,company,wikipedia,description,id
0,"{'meters': 22.25, 'feet': 73}","{'meters': 1.68, 'feet': 5.5}","{'kg': 30146, 'lb': 66460}","{'thrust_sea_level': {'kN': 420, 'lbf': 94000}...","{'thrust': {'kN': 31, 'lbf': 7000}, 'payloads'...","{'isp': {'sea_level': 267, 'vacuum': 304}, 'th...","{'number': 0, 'material': None}","[{'id': 'leo', 'name': 'Low Earth Orbit', 'kg'...","[https://imgur.com/DaCfMsj.jpg, https://imgur....",Falcon 1,...,2,0,6700000,40,2006-03-24,Republic of the Marshall Islands,SpaceX,https://en.wikipedia.org/wiki/Falcon_1,The Falcon 1 was an expendable launch system p...,5e9d0d95eda69955f709d1eb
1,"{'meters': 70, 'feet': 229.6}","{'meters': 3.7, 'feet': 12}","{'kg': 549054, 'lb': 1207920}","{'thrust_sea_level': {'kN': 7607, 'lbf': 17100...","{'thrust': {'kN': 934, 'lbf': 210000}, 'payloa...","{'isp': {'sea_level': 288, 'vacuum': 312}, 'th...","{'number': 4, 'material': 'carbon fiber'}","[{'id': 'leo', 'name': 'Low Earth Orbit', 'kg'...",[https://farm1.staticflickr.com/929/2878733830...,Falcon 9,...,2,0,50000000,98,2010-06-04,United States,SpaceX,https://en.wikipedia.org/wiki/Falcon_9,Falcon 9 is a two-stage rocket designed and ma...,5e9d0d95eda69973a809d1ec
2,"{'meters': 70, 'feet': 229.6}","{'meters': 12.2, 'feet': 39.9}","{'kg': 1420788, 'lb': 3125735}","{'thrust_sea_level': {'kN': 22819, 'lbf': 5130...","{'thrust': {'kN': 934, 'lbf': 210000}, 'payloa...","{'isp': {'sea_level': 288, 'vacuum': 312}, 'th...","{'number': 12, 'material': 'carbon fiber'}","[{'id': 'leo', 'name': 'Low Earth Orbit', 'kg'...",[https://farm5.staticflickr.com/4599/385838292...,Falcon Heavy,...,2,2,90000000,100,2018-02-06,United States,SpaceX,https://en.wikipedia.org/wiki/Falcon_Heavy,With the ability to lift into orbit over 54 me...,5e9d0d95eda69974db09d1ed
3,"{'meters': 118, 'feet': 387}","{'meters': 9, 'feet': 30}","{'kg': 1335000, 'lb': 2943000}","{'thrust_sea_level': {'kN': 128000, 'lbf': 287...","{'thrust': {'kN': 1957, 'lbf': 440000}, 'paylo...","{'isp': {'sea_level': 330, 'vacuum': 380}, 'th...","{'number': 6, 'material': 'stainless steel'}","[{'id': 'leo', 'name': 'Low Earth Orbit', 'kg'...",[https://live.staticflickr.com/65535/489541389...,Starship,...,2,0,7000000,0,2021-12-01,United States,SpaceX,https://en.wikipedia.org/wiki/SpaceX_Starship,Starship and Super Heavy Rocket represent a fu...,5e9d0d96eda699382d09d1ee

this did not work. I looked up how to individually extract data from each column, but I will not be doing that here. there are still quite a few normal columns to work with

*Requirement: Find and print TWO descriptive statistics about your data*

1. I did mean of character count of the 'success_rate_pct' (success percentage) column
2.  Found the maximum value of the 'boosters' column

In [28]:
mean_length = rockets['success_rate_pct'].mean()
print(mean_length)

59.5

In [29]:
max_boosters = rockets['boosters'].max()

print(max_boosters)

2

*Requirement: Print the second and third column of my dataframe*

In [30]:
print(rockets.iloc[:, 1:3])

                         diameter                            mass
0   {'meters': 1.68, 'feet': 5.5}      {'kg': 30146, 'lb': 66460}
1     {'meters': 3.7, 'feet': 12}   {'kg': 549054, 'lb': 1207920}
2  {'meters': 12.2, 'feet': 39.9}  {'kg': 1420788, 'lb': 3125735}
3       {'meters': 9, 'feet': 30}  {'kg': 1335000, 'lb': 2943000}

*Requirement: query in Pandas to select a particular set of your data.*

I'm making a mask to filter and show only the rows where the booster column value is '2'

In [32]:

# Create a mask to filter rows with 'boosters' column value equal to 2
mask = rockets['boosters'] == 2

# Apply the mask to the DataFrame to get filtered rows
boosters_2_mask = rockets[mask]

print(boosters_2_mask)

                          height                        diameter  \
2  {'meters': 70, 'feet': 229.6}  {'meters': 12.2, 'feet': 39.9}

                             mass  \
2  {'kg': 1420788, 'lb': 3125735}

                                         first_stage  \
2  {'thrust_sea_level': {'kN': 22819, 'lbf': 5130...

                                        second_stage  \
2  {'thrust': {'kN': 934, 'lbf': 210000}, 'payloa...

                                             engines  \
2  {'isp': {'sea_level': 288, 'vacuum': 312}, 'th...

                                 landing_legs  \
2  {'number': 12, 'material': 'carbon fiber'}

                                     payload_weights  \
2  [{'id': 'leo', 'name': 'Low Earth Orbit', 'kg'...

                                       flickr_images          name  ...  \
2  [https://farm5.staticflickr.com/4599/385838292...  Falcon Heavy  ...

  stages  boosters  cost_per_launch  success_rate_pct  first_flight  \
2      2         2         90000000               100    2018-02-06

         country company                                   wikipedia  \
2  United States  SpaceX  https://en.wikipedia.org/wiki/Falcon_Heavy

                                         description                        id
2  With the ability to lift into orbit over 54 me...  5e9d0d95eda69974db09d1ed

[1 rows x 22 columns]